# strict: true
theme:
  name: material
  # custom_dir: overrides
  # favicon: assets/favicon.png
  font:
    text: Montserrat
  # logo: assets/logo.png
  palette:
    primary: green
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - search.suggest

plugins:
  - search
  - roamlinks

extra_css:
  - assets/style.css
extra_javascript:
  - assets/script.js
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - toc:
      permalink: true
      title: Table of Contents
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - footnotes

repo_url: https://github.com/dlccyes/CollegeNotes
# logo:
site_name: Los Libros
nav:
- About: README.md
- Database: database.md
- "broken-earth/Broken Earth.md"
- Cosmere: 
  - Cosmere/Cosmere.md
  - Mistborn: "Cosmere/Mistborn (book).md"
  - The Stormlight Archive: "Cosmere/Stormlight/The Stormlight Archive.md"
- Blog ⧉: https://dlccyes.github.io/blog

extra:
  social:
    - icon: fontawesome/brands/pied-piper-alt
      link: https://dlccyes.github.io
    - icon: fontawesome/brands/medium
      link: https://dlccyes.github.io/blog
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/derrick-lin
    - icon: fontawesome/brands/github
      link: https://github.com/dlccyes
